version: '3'
services:
  fullstack-mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports: 
      - 3306:3306
    #volumes:
    #  - database_mysql:/var/lib/mysql
    networks:
      - fullstack
  sqadcast:
    container_name: sqadcast
    build: .
    ports: 
      - 5000:5000 
    restart: on-failure
    #volumes:
    #  - api:/usr/src/app/
    depends_on:
      - fullstack-mysql          
    networks:
      - fullstack
# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
